"""New migration

Revision ID: 2c0682885eb8
Revises: 97ef14dea897
Create Date: 2025-07-22 12:07:35.627132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c0682885eb8'
down_revision: Union[str, None] = '97ef14dea897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=True),
    sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('equipment_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('training_plans', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('training_plans', sa.Column('workout_goal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('workout_goal_llm_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('fitness_level_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('experience_level_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'experience_level_description')
    op.drop_column('training_plans', 'fitness_level_description')
    op.drop_column('training_plans', 'workout_goal_llm_context')
    op.drop_column('training_plans', 'workout_goal_id')
    op.drop_column('training_plans', 'age')
    op.drop_table('training_profiles')
    # ### end Alembic commands ###
