"""New migration

Revision ID: 47840fcb30a4
Revises: df26bdf3617a
Create Date: 2025-07-23 09:43:00.199575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47840fcb30a4'
down_revision: Union[str, None] = 'df26bdf3617a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_profiles', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('training_profiles_training_plan_id_fkey', 'training_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'training_profiles', 'users', ['user_id'], ['id'])
    op.drop_column('training_profiles', 'training_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_profiles', sa.Column('training_plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training_profiles', type_='foreignkey')
    op.create_foreign_key('training_profiles_training_plan_id_fkey', 'training_profiles', 'training_plans', ['training_plan_id'], ['id'])
    op.drop_column('training_profiles', 'user_id')
    # ### end Alembic commands ###
