"""New migration

Revision ID: 21faffd62fb0
Revises: 7d6feacfde9d
Create Date: 2025-06-23 08:06:31.800706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21faffd62fb0'
down_revision: Union[str, None] = '7d6feacfde9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('other_regular_activities', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('training_plans', 'include_cardio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('include_cardio', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('training_plans', 'comments')
    op.drop_column('training_plans', 'other_regular_activities')
    # ### end Alembic commands ###
