"""New migration

Revision ID: a8c5acc25a40
Revises: 5b5f78a8e5a1
Create Date: 2025-07-31 17:04:49.851924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8c5acc25a40'
down_revision: Union[str, None] = '5b5f78a8e5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    settag_enum = sa.Enum('warm_up', name='settag')
    settag_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column
    op.add_column('sets', sa.Column('tag', settag_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'tag')
    
    # Drop the enum type
    settag_enum = sa.Enum('warm_up', name='settag')
    settag_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
