"""json für trainingsprinzipien

Revision ID: 96b8230afa20
Revises: b37566c9bd13
Create Date: 2025-05-22 12:26:13.542940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96b8230afa20'
down_revision: Union[str, None] = 'b37566c9bd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('training_principles_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'training_principles_json')
    # ### end Alembic commands ###
