"""Add onboarding_completed field to users

Revision ID: 82a801fa724a
Revises: 0c852e14b102
Create Date: 2025-05-27 20:00:13.870471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82a801fa724a'
down_revision: Union[str, None] = '0c852e14b102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    
    # Step 2: Set default value for existing users (assume they completed onboarding if they exist)
    op.execute("UPDATE users SET onboarding_completed = true WHERE onboarding_completed IS NULL")
    
    # Step 3: Make column NOT NULL
    op.alter_column('users', 'onboarding_completed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
