"""add workout_id to activity_log and create workout_feedback

Revision ID: 019af53fe9ee
Revises: c5f074acf1e9
Create Date: 2025-05-12 11:02:46.874601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019af53fe9ee'
down_revision: Union[str, None] = 'c5f074acf1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_feedback')
    op.add_column('training_history', sa.Column('workout_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training_history', 'workouts', ['workout_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_history', type_='foreignkey')
    op.drop_column('training_history', 'workout_id')
    op.create_table('workout_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intensity_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='workout_feedback_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='workout_feedback_workout_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workout_feedback_pkey')
    )
    # ### end Alembic commands ###
