"""New migration

Revision ID: a90356a832a5
Revises: e6eddc686316
Create Date: 2025-04-28 20:12:05.439550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a90356a832a5'
down_revision: Union[str, None] = 'e6eddc686316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcase_feedbacks', sa.Column('feedback_rating', sa.Integer(), nullable=True))
    op.drop_column('showcase_feedbacks', 'feedback_assessment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcase_feedbacks', sa.Column('feedback_assessment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('showcase_feedbacks', 'feedback_rating')
    # ### end Alembic commands ###
