"""Add uid column to exercises table

Revision ID: e04211969877
Revises: d05733b51b9f
Create Date: 2025-08-01 15:20:28.578266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e04211969877'
down_revision: Union[str, None] = 'd05733b51b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_exercises_uid'), 'exercises', ['uid'], unique=True)
    
    # Populate existing exercises with UIDs
    from uuid import uuid4
    from sqlalchemy import text
    
    # Get all existing exercises and assign UIDs
    connection = op.get_bind()
    result = connection.execute(text("SELECT id FROM exercises WHERE uid IS NULL"))
    for row in result:
        uid = str(uuid4())
        connection.execute(
            text("UPDATE exercises SET uid = :uid WHERE id = :id"),
            {"uid": uid, "id": row[0]}
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_uid'), table_name='exercises')
    op.drop_column('exercises', 'uid')
    # ### end Alembic commands ###
