"""sync database with current models

Revision ID: 4bd8c1959e14
Revises: 81603cd6b6f8
Create Date: 2025-05-29 09:21:51.722887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd8c1959e14'
down_revision: Union[str, None] = '81603cd6b6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_page_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('training_goals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('training_types', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_apps', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_willingness', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_page_surveys_email'), 'landing_page_surveys', ['email'], unique=False)
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', postgresql.ENUM('USER', 'ADMIN', 'MODERATOR', name='userrole'), autoincrement=False, nullable=False))
    op.drop_column('users', 'onboarding_completed')
    op.drop_index(op.f('ix_landing_page_surveys_email'), table_name='landing_page_surveys')
    op.drop_table('landing_page_surveys')
    # ### end Alembic commands ###
