"""New migration

Revision ID: 40e8acb1436a
Revises: 86d813f818ac
Create Date: 2025-06-24 22:26:47.065100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40e8acb1436a'
down_revision: Union[str, None] = '86d813f818ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'is_amrap')
    op.drop_column('blocks', 'amrap_duration_minutes')
    op.drop_constraint('users_training_plan_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'training_plans', ['training_plan_id'], ['id'])
    op.drop_constraint('workouts_training_plan_id_fkey', 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'training_plans', ['training_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.create_foreign_key('workouts_training_plan_id_fkey', 'workouts', 'training_plans', ['training_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_training_plan_id_fkey', 'users', 'training_plans', ['training_plan_id'], ['id'], ondelete='SET NULL')
    op.add_column('blocks', sa.Column('amrap_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('is_amrap', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
