"""New migration

Revision ID: facb9f1fa61a
Revises: 93dfd5283dbf
Create Date: 2025-05-16 17:24:05.669179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'facb9f1fa61a'
down_revision: Union[str, None] = '93dfd5283dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'notes')
    # Set all include_cardio values to 'false' (string) before type change
    op.execute("UPDATE training_plans SET include_cardio = 'false' WHERE include_cardio IS NOT NULL;")
    op.alter_column(
        'training_plans',
        'include_cardio',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="include_cardio::boolean"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'include_cardio',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('sets', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
