"""New migration

Revision ID: 7d6feacfde9d
Revises: 2ab9ebcb7a71
Create Date: 2025-06-03 11:27:19.973783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d6feacfde9d'
down_revision: Union[str, None] = '2ab9ebcb7a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('superset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'superset_id')
    # ### end Alembic commands ###
