"""fix app_feedback id autoincrement properly

Revision ID: aa7feba8a761
Revises: 1828cb213ebf
Create Date: 2025-05-26 12:11:18.010359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa7feba8a761'
down_revision: Union[str, None] = '1828cb213ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
