"""New migration

Revision ID: 55d521a42666
Revises: a4526f1fb6e4
Create Date: 2025-04-28 15:30:54.816080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55d521a42666'
down_revision: Union[str, None] = 'a4526f1fb6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase_waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showcase_waitlist_email'), 'showcase_waitlist', ['email'], unique=True)
    op.drop_index('ix_waitlist_email', table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waitlist_pkey')
    )
    op.create_index('ix_waitlist_email', 'waitlist', ['email'], unique=True)
    op.drop_index(op.f('ix_showcase_waitlist_email'), table_name='showcase_waitlist')
    op.drop_table('showcase_waitlist')
    # ### end Alembic commands ###
