"""New migration

Revision ID: 75d41299c50c
Revises: 3e5b59ef1466
Create Date: 2025-04-24 08:54:02.796691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75d41299c50c'
down_revision: Union[str, None] = '3e5b59ef1466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Enum-Typ anlegen (falls nicht schon vorhanden)
    workoutstatus = sa.Enum('INCOMPLETE', 'COMPLETED', name='workoutstatus')
    workoutstatus.create(op.get_bind(), checkfirst=True)

    # 2. Spalte mit nullable=True hinzufügen
    op.add_column('workouts', sa.Column('status', workoutstatus, nullable=True))

    # 3. Alle bestehenden Zeilen auf 'INCOMPLETE' setzen
    op.execute("UPDATE workouts SET status='INCOMPLETE' WHERE status IS NULL")

    # 4. Spalte auf NOT NULL setzen
    op.alter_column('workouts', 'status', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'status')
    # ### end Alembic commands ###
