"""fix_app_feedback_id_autoincrement

Revision ID: 1828cb213ebf
Revises: 731d69c93b5f
Create Date: 2025-05-26 12:00:52.337625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1828cb213ebf'
down_revision: Union[str, None] = '731d69c93b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
