"""New migration

Revision ID: 0a0408e665e6
Revises: 8fb5cb8f27c2
Create Date: 2025-06-29 22:14:00.770689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a0408e665e6'
down_revision: Union[str, None] = '8fb5cb8f27c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'training_plans', ['user_id'])
    op.create_foreign_key(None, 'training_plans', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_training_plan_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'training_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('training_plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_training_plan_id_fkey', 'users', 'training_plans', ['training_plan_id'], ['id'])
    op.drop_constraint(None, 'training_plans', type_='foreignkey')
    op.drop_constraint(None, 'training_plans', type_='unique')
    op.alter_column('training_plans', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
