"""New migration

Revision ID: c5b612dcda75
Revises: 1b5c64ae59a9
Create Date: 2025-05-13 15:19:27.919300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b612dcda75'
down_revision: Union[str, None] = '1b5c64ae59a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_history')
    op.add_column('training_plans', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('training_plans', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('training_plans', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('training_plans', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('training_plans', sa.Column('goal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('goal_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('fitness_level', sa.Integer(), nullable=True))
    op.add_column('training_plans', sa.Column('experience_level', sa.Integer(), nullable=True))
    op.add_column('training_plans', sa.Column('training_frequency', sa.Integer(), nullable=True))
    op.add_column('training_plans', sa.Column('equipment_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('include_cardio', sa.Boolean(), nullable=True))
    op.add_column('training_plans', sa.Column('mobility_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_plans', sa.Column('training_principles', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'training_principles')
    op.drop_column('training_plans', 'mobility_restrictions')
    op.drop_column('training_plans', 'include_cardio')
    op.drop_column('training_plans', 'equipment_details')
    op.drop_column('training_plans', 'training_frequency')
    op.drop_column('training_plans', 'experience_level')
    op.drop_column('training_plans', 'fitness_level')
    op.drop_column('training_plans', 'goal_details')
    op.drop_column('training_plans', 'goal_type')
    op.drop_column('training_plans', 'weight')
    op.drop_column('training_plans', 'height')
    op.drop_column('training_plans', 'age')
    op.drop_column('training_plans', 'birthdate')
    op.drop_column('training_plans', 'gender')
    op.create_table('training_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rest_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name='training_history_set_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='training_history_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='training_history_workout_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='training_history_pkey')
    )
    # ### end Alembic commands ###
