"""sync database with current models

Revision ID: 4bd8c1959e14
Revises: 81603cd6b6f8
Create Date: 2025-05-29 09:21:51.722887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd8c1959e14'
down_revision: Union[str, None] = '81603cd6b6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All changes already exist in database - making this a no-op migration
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Since upgrade is no-op, downgrade is also no-op
    pass
    # ### end Alembic commands ###
