"""New migration

Revision ID: cd42346dc8e2
Revises: a985099677ed
Create Date: 2025-04-28 15:27:23.511688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd42346dc8e2'
down_revision: Union[str, None] = 'a985099677ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcase_training_plans', sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('showcase_training_plans', sa.Column('restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('showcase_training_plans', sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('showcase_training_plans', sa.Column('session_duration', sa.Integer(), nullable=False))
    op.add_column('showcase_training_plans', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('showcase_training_plans', sa.Column('history', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showcase_training_plans', 'history')
    op.drop_column('showcase_training_plans', 'description')
    op.drop_column('showcase_training_plans', 'session_duration')
    op.drop_column('showcase_training_plans', 'equipment')
    op.drop_column('showcase_training_plans', 'restrictions')
    op.drop_column('showcase_training_plans', 'goal')
    # ### end Alembic commands ###
