"""New migration

Revision ID: 5b5f78a8e5a1
Revises: 4b5053330fe2
Create Date: 2025-07-23 10:07:30.560069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b5f78a8e5a1'
down_revision: Union[str, None] = '4b5053330fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_profiles', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_profiles', 'name')
    # ### end Alembic commands ###
