"""New migration

Revision ID: 99694c0e60b6
Revises: f8edeb0649cd
Create Date: 2025-05-13 19:36:16.833673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99694c0e60b6'
down_revision: Union[str, None] = 'f8edeb0649cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###)
    op.add_column('training_plans', sa.Column('goal_types', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('training_plans', 'include_cardio',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('training_plans', 'goal_type')
    op.drop_column('training_plans', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training_plans', sa.Column('goal_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('training_plans', 'include_cardio',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('training_plans', 'goal_types')
    op.create_table('training_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rest_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name='training_history_set_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='training_history_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='training_history_workout_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='training_history_pkey')
    )
    # ### end Alembic commands ###
