"""New migration

Revision ID: 1c416c4e4e7a
Revises: 21faffd62fb0
Create Date: 2025-06-23 11:45:55.090727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c416c4e4e7a'
down_revision: Union[str, None] = '21faffd62fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'training_principles_json')
    op.drop_column('training_plans', 'training_principles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('training_principles', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training_plans', sa.Column('training_principles_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
