"""New migration

Revision ID: 3e5b59ef1466
Revises: 70563d1f1831
Create Date: 2025-04-23 22:00:16.398440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e5b59ef1466'
down_revision: Union[str, None] = '70563d1f1831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'workouts_per_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('workouts_per_week', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
