"""New migration

Revision ID: d4726ff1edca
Revises: 7aeb2be7903a
Create Date: 2025-05-04 12:43:55.085654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4726ff1edca'
down_revision: Union[str, None] = '7aeb2be7903a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('training_history_set_id_fkey', 'training_history', type_='foreignkey')
    op.create_foreign_key(None, 'training_history', 'sets', ['set_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_history', type_='foreignkey')
    op.create_foreign_key('training_history_set_id_fkey', 'training_history', 'sets', ['set_id'], ['id'])
    # ### end Alembic commands ###
