"""New migration

Revision ID: 93dfd5283dbf
Revises: f97fc7edc7d8
Create Date: 2025-05-14 14:10:55.026946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93dfd5283dbf'
down_revision: Union[str, None] = 'f97fc7edc7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('sets', sa.Column('reps', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('distance', sa.Float(), nullable=True))
    op.drop_column('sets', 'execution_distance')
    op.drop_column('sets', 'execution_weight')
    op.drop_column('sets', 'plan_reps')
    op.drop_column('sets', 'execution_reps')
    op.drop_column('sets', 'plan_distance')
    op.drop_column('sets', 'plan_duration')
    op.drop_column('sets', 'plan_weight')
    op.drop_column('sets', 'execution_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('execution_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('plan_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('plan_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('plan_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('execution_reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('plan_reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('execution_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sets', sa.Column('execution_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sets', 'distance')
    op.drop_column('sets', 'duration')
    op.drop_column('sets', 'reps')
    op.drop_column('sets', 'weight')
    # ### end Alembic commands ###
