"""Add created_at and updated_at to Workout model

Revision ID: 300fa80e0c38
Revises: 75d41299c50c
Create Date: 2025-04-24 09:25:28.226378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '300fa80e0c38'
down_revision: Union[str, None] = '75d41299c50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
