"""New migration

Revision ID: 97ef14dea897
Revises: e8d0e6109369
Create Date: 2025-07-16 21:09:28.809374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97ef14dea897'
down_revision: Union[str, None] = 'e8d0e6109369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('muscle_group_load', sa.JSON(), nullable=True))
    op.add_column('workouts', sa.Column('focus_derivation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'focus_derivation')
    op.drop_column('workouts', 'muscle_group_load')
    # ### end Alembic commands ###
