"""New migration

Revision ID: f8edeb0649cd
Revises: 89b963b73d92
Create Date: 2025-05-13 16:06:39.773212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8edeb0649cd'
down_revision: Union[str, None] = '89b963b73d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE training_plans ALTER COLUMN session_duration TYPE INTEGER USING session_duration::integer")
    op.drop_column('training_plans', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute("ALTER TABLE training_plans ALTER COLUMN session_duration TYPE VARCHAR USING session_duration::varchar")
    # ### end Alembic commands ###
