"""New migration

Revision ID: ec8ef4ffe14b
Revises: 844710d9860c
Create Date: 2025-04-28 14:10:04.932566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec8ef4ffe14b'
down_revision: Union[str, None] = '844710d9860c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase_questionnaire_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showcase_questionnaire_templates_questionnaire_id'), 'showcase_questionnaire_templates', ['questionnaire_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showcase_questionnaire_templates_questionnaire_id'), table_name='showcase_questionnaire_templates')
    op.drop_table('showcase_questionnaire_templates')
    # ### end Alembic commands ###
