"""New migration

Revision ID: 6d0f8c5fd0d7
Revises: 54af82d51739
Create Date: 2025-04-28 15:47:55.482997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d0f8c5fd0d7'
down_revision: Union[str, None] = '54af82d51739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('showcase_feedbacks', 'training_plan_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='training_plan_id::integer')
    op.create_foreign_key(None, 'showcase_feedbacks', 'showcase_training_plans', ['training_plan_id'], ['id'])
    op.alter_column('showcase_training_plans', 'session_duration',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('showcase_training_plans', 'session_duration',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'showcase_feedbacks', type_='foreignkey')
    op.alter_column('showcase_feedbacks', 'training_plan_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
