"""New migration

Revision ID: e8d0e6109369
Revises: f27054a29151
Create Date: 2025-07-07 16:41:21.648233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8d0e6109369'
down_revision: Union[str, None] = 'f27054a29151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('revised_workout_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'revised_workout_data')
    # ### end Alembic commands ###
