"""New migration

Revision ID: 3fef24c8b1f7
Revises: e04211969877
Create Date: 2025-08-02 14:00:13.556200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fef24c8b1f7'
down_revision: Union[str, None] = 'e04211969877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('duration_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'duration_min')
    # ### end Alembic commands ###
