"""New migration

Revision ID: 4b5053330fe2
Revises: 47840fcb30a4
Create Date: 2025-07-23 09:53:32.967706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b5053330fe2'
down_revision: Union[str, None] = '47840fcb30a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_profiles', sa.Column('equipment_llm_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_profiles', 'equipment_llm_context')
    # ### end Alembic commands ###
