"""add exercise descriptions table

Revision ID: f4c3dceb4970
Revises: 4fbe8727269d
Create Date: 2025-06-30 18:43:00.632531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4c3dceb4970'
down_revision: Union[str, None] = '4fbe8727269d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_descriptions',
    sa.Column('name_german', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_english', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description_german', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('equipment_options', sa.JSON(), nullable=True),
    sa.Column('target_muscle_groups', sa.JSON(), nullable=True),
    sa.Column('execution_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name_german')
    )
    # ### end Alembic commands ###
 

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_descriptions')
    # ### end Alembic commands ###
