"""create landing_page_surveys table with sqlmodel

Revision ID: 81603cd6b6f8
Revises: e6b48f05b930
Create Date: 2025-05-29 08:58:58.371092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81603cd6b6f8'
down_revision: Union[str, None] = 'e6b48f05b930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_page_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('training_goals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('training_types', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_apps', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_willingness', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_page_surveys_email'), 'landing_page_surveys', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_page_surveys_email'), table_name='landing_page_surveys')
    op.drop_table('landing_page_surveys')
    # ### end Alembic commands ###
