"""New migration

Revision ID: e444f0cd83a1
Revises: 1c416c4e4e7a
Create Date: 2025-06-23 14:27:50.155820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e444f0cd83a1'
down_revision: Union[str, None] = '1c416c4e4e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('workout_styles', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'workout_styles')
    # ### end Alembic commands ###
