"""New migration

Revision ID: 60065a338749
Revises: f9065f8fd650
Create Date: 2025-06-23 15:56:17.981523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60065a338749'
down_revision: Union[str, None] = 'f9065f8fd650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('exercises', sa.Column('is_amrap', sa.Boolean(), nullable=True))
    
    # Update all existing records to set is_amrap = False
    op.execute("UPDATE exercises SET is_amrap = FALSE WHERE is_amrap IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('exercises', 'is_amrap', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'is_amrap')
    # ### end Alembic commands ###
