"""New migration

Revision ID: c5f074acf1e9
Revises: 8785ecf9cea6
Create Date: 2025-05-04 14:28:27.106232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5f074acf1e9'
down_revision: Union[str, None] = '8785ecf9cea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_plans', 'restrictions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_plans', 'equipment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_plans', 'session_duration',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'session_duration',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_plans', 'equipment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_plans', 'restrictions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_plans', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
