"""New migration

Revision ID: b68b371dd77b
Revises: 1a1d8f349bc5
Create Date: 2025-05-04 13:09:04.225916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b68b371dd77b'
down_revision: Union[str, None] = '1a1d8f349bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blocks_workout_id_fkey', 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exercises_block_id_fkey', 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'blocks', ['block_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sets_exercise_id_fkey', 'sets', type_='foreignkey')
    op.create_foreign_key(None, 'sets', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.create_foreign_key('sets_exercise_id_fkey', 'sets', 'exercises', ['exercise_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_foreign_key('exercises_block_id_fkey', 'exercises', 'blocks', ['block_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key('blocks_workout_id_fkey', 'blocks', 'workouts', ['workout_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
