"""New migration

Revision ID: 64f2f8a0cccc
Revises: 28697dc74903
Create Date: 2025-05-12 21:41:45.135876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64f2f8a0cccc'
down_revision: Union[str, None] = '28697dc74903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_plans', 'restrictions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_plans', 'equipment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_plans', 'session_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('training_plans', 'workouts_per_week')
    op.drop_column('training_plans', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('description', sa.VARCHAR(), server_default=sa.text("'Automatisch generierter Trainingsplan'::character varying"), autoincrement=False, nullable=False))
    op.add_column('training_plans', sa.Column('workouts_per_week', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.alter_column('training_plans', 'session_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_plans', 'equipment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_plans', 'restrictions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_plans', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
