"""New migration

Revision ID: 595e19ff6577
Revises: b5bd20d2f42b
Create Date: 2025-04-24 16:29:42.222840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '595e19ff6577'
down_revision: Union[str, None] = 'b5bd20d2f42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'description')
    # ### end Alembic commands ###
